aws_dbt_snowflake_project:
  outputs:
    dev:
      account: BZPHLGG-KI09570
      database: AIRBNB
      password: Shuvendu898435
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: SHUVENDU
      warehouse: COMPUTE_WH
  target: dev
